### PR TITLE
Feature/5 multiremote support

### PR DESCRIPTION
**Pull request by elaichenkov**
feature: #5 Multiremote support

Added:
* multiremote tests
* util functions for getting element and elements

Updated:
* arrow functions > function declaration
* use `this` instead of the `browser` instance
* tests

### CODE REVIEW

**Review by christian-bromann — COMMENTED** [review]
How difficult is it to make this work with multiremote as well:

```js
      it('should verify urlContains method', async () => {
        await browser.url('https://webdriver.io');
        expect(await urlContains('io')).toBe(true);
      });
```

?

**Comment by elaichenkov** [comment]
> How difficult is it to make this work with multiremote as well:
> 
> ```js
>       it('should verify urlContains method', async () => {
>         await browser.url('https://webdriver.io');
>         expect(await urlContains('io')).toBe(true);
>       });
> ```
> 
> ?

It will not work with a single instance and multiremote either.
Because we have to return a function.
So, this function `urlContains('io')` returns another function where we have logic.
Maybe you meant to make it `urlContains('io')()`?
I can check `this` and if it's `undefined`, then I'll use the `browser` instead of `this`, and in multiremote case, the `urlContains('io')()` method will return an array of booleans`[false, true]`, and in a single instance, the `urlContains('io')()` method will return just boolean.

**Comment by christian-bromann** [comment]
Yeah, in the original issue my example was referring to a single browser instance:
```js
const matrix = await multiremote({ browser1: {...} })
await matrix.browser1.waitUntil(
   titleContains('expected conditions'),
   {
      timeout: 5000,
      timeoutMsg: 'expected title....'
   }
)
```

but I wonder if we can also allow:

```js
await matrix.waitUntil(
   titleContains('expected conditions'),
   {
      timeout: 5000,
      timeoutMsg: 'expected title....'
   }
)
```

in which case the conditions need to be fulfilled for all browser instances.

**Comment by elaichenkov** [comment]
> Yeah, in the original issue my example was referring to a single browser instance:
> 
> ```js
> const matrix = await multiremote({ browser1: {...} })
> await matrix.browser1.waitUntil(
>    titleContains('expected conditions'),
>    {
>       timeout: 5000,
>       timeoutMsg: 'expected title....'
>    }
> )
> ```
> 
> but I wonder if we can also allow:
> 
> ```js
> await matrix.waitUntil(
>    titleContains('expected conditions'),
>    {
>       timeout: 5000,
>       timeoutMsg: 'expected title....'
>    }
> )
> ```
> 
> in which case the conditions need to be fulfilled for all browser instances.

Actually, it works now.
I've just tested the following cases:

```typescript

      // Passed
      it('should pass for specific instance urlContains method', async () => {
        await browser.url('https://the-internet.herokuapp.com')
        await browserB.url('https://webdriver.io/docs/wdio-wait-for/#api');
    
        //@ts-ignore
        await browser.browserB.waitUntil(
          titleContains('expected conditions'),
          {
            timeout: 1000,
            timeoutMsg: 'expected title for browser B'
          }
        )
      });

      // Passed
      it('should pass for two instances urlContains method', async () => {
        await browser.url('https://webdriver.io/docs/wdio-wait-for/#api')

        await browser.waitUntil(
          titleContains('expected conditions'),
          {
            timeout: 1000,
            timeoutMsg: 'expected title for two instances'
          }
        )
      });

       // Failed
      it('should fail for two instances urlContains method', async () => {
        await browser.url('https://the-internet.herokuapp.com');
        await browserB.url('https://webdriver.io/docs/wdio-wait-for/#api');

        await browser.waitUntil(
          titleContains('expected conditions'),
          {
            timeout: 1000,
            timeoutMsg: 'expected title for two instances'
          }
        )
      });
```

**Comment by christian-bromann** [comment]
Do we need to enhance the tests or do they already cover this?

**Comment by elaichenkov** [comment]
They cover it, in our tests I do the same, except I don't use the `waitUntil` method to focus only on our prediction functions.

**Review by christian-bromann — APPROVED** [review]
Awesome, shit it :shipit:

**Comment by christian-bromann** [comment]
@elaichenkov to release trigger the `Manual NPM Publish` action and set `Release type` to `minor` and keep `NPM tag` at `latest`

**Comment by elaichenkov** [comment]
@christian-bromann 
Thank you!
There were few issues with `npm` script and `github` token, which I've fixed and it works now. Published `2.1.0`

**Pull request merged**
